### ISSUE TITLE
Docker rebuilding failing

### ISSUE THREAD

**Issue by harsh4870** [vbhayden/keycloak-federation-examples#1]
Docker step generating error at : https://github.com/vbhayden/keycloak-federation-examples/blob/master/keycloak/Dockerfile

```
# Add the PostgreSQL module to the server
#
RUN cd /tmp && \
    curl -O http://central.maven.org/maven2/org/postgresql/postgresql/$POSTGRES_JDBC_VERSION/postgresql-$POSTGRES_JDBC_VERSION.jar && \
    mkdir -p /opt/jboss/keycloak/modules/system/layers/base/org/postgresql/main && \
    mv postgresql-$POSTGRES_JDBC_VERSION.jar /opt/jboss/keycloak/modules/system/layers/base/org/postgresql/main/postgresql.jar
```
Curl is not longer working i think.

**Comment by vbhayden** [comment]
Good catch, updated this on the version I use for other projects but forgot about this one.  Didn't know about the `repo1.` subdomain -- had been using the `search.maven.org` instead. 

Thanks!
